### ISSUE TITLE
Present result

### ISSUE THREAD

**Issue by makjohansson** [kvillt/psa#7]
design the output from the calculations, should be responsive

**Comment by kvillt** [comment]
We should add Result boxes, since we will have more than a single result

**Comment by kvillt** [comment]
Would also be nice with a small text box for a description for description of tests

**Comment by makjohansson** [comment]
Hur många resultat kommer vi ha? Har du någon tanke om hur det kan se ut?

mån 18 jan. 2021 kl. 18:20 skrev Jesper <notifications@github.com>:

**Comment by kvillt** [comment]
Som det är nu så vill jag ha ett mann whitney u test som kommer med ett U värde och ett p värde.
Samt ett normalitetstest

**Comment by kvillt** [comment]
Jag har lagt till testerna så de beräknas och returneras
